bundler_args: --without development
language: ruby
rvm:
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
